const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'

const LOGOUT = 'LOGOUT'

const ALLPRODUCTS_REQUEST = 'ALLPRODUCTS_REQUEST'
const ALLPRODUCTS_SUCCESS = 'ALLPRODUCTS_SUCCESS'
const ALLPRODUCTS_FAILURE = 'ALLPRODUCTS_FAILURE'

const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST'
const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE'

const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

const LOADING = 'LOADING';
const LOADED = 'LOADED';

module.exports = {
    LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILURE,
    LOGOUT,
    ALLPRODUCTS_REQUEST,ALLPRODUCTS_SUCCESS,ALLPRODUCTS_FAILURE,
    PRODUCT_REQUEST,PRODUCT_SUCCESS,PRODUCT_FAILURE,
    EDIT_PRODUCT_REQUEST,EDIT_PRODUCT_SUCCESS,EDIT_PRODUCT_FAILURE,
    ADD_PRODUCT_REQUEST,ADD_PRODUCT_SUCCESS,ADD_PRODUCT_FAILURE,
    DELETE_PRODUCT_REQUEST,DELETE_PRODUCT_SUCCESS,DELETE_PRODUCT_FAILURE,
    LOADING,LOADED

}